version: '3'
services:
  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: nginx
    container_name: nginx_lb
    ports:
      - "8000:80"
    networks: 
      - minha-rede
    depends_on:
      - "postgresql_one"
      - "postgresql_two"

  postgresql_one:
    image: postgres
    container_name: postgresql_one_lb
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Cob.2403"
    ports:
      - "5431:5432"
    volumes:
      - /home/ercosta/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data
    networks:
      - minha-rede

  postgresql_two:
    image: postgres
    container_name: postgresql_two_lb
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Cob.2403"
    ports:
      - "5433:5432"
    volumes:
      - /home/ercosta/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data
    networks:
      - minha-rede

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_lb
    environment:
      PGADMIN_DEFAULT_EMAIL: "ercosta90@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Cob.2403"
    ports:
      - "6543:80"
    depends_on:
      - postgresql_one
      - postgresql_two
    networks:
      - minha-rede

networks: 
    minha-rede: